<center>
<img src="https://openclipart.org/image/400px/215664"
    style="width:35%;">
    <h1 style="color: #00BFFF;">APIs</h1>
</center>

<h2 style="color: #008080;">APIs with Python</h2>

You can make requests to RESTful APIs using libraries like `requests` (same we used for web scraping!).

In [ ]:
# pip install requests

<h1 style="color: #00BFFF;">00 | Use case: International Space Station</h1>

In [1]:
# 📚 Basic libraries
import requests

<h1 style="color: #00BFFF;">01 | Data Extraction</h1>

<center>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/STS-134_EVA4_view_to_the_Space_Shuttle_Endeavour.jpg/1920px-STS-134_EVA4_view_to_the_Space_Shuttle_Endeavour.jpg"
    style="width:40%;">
</center>

Let's get information from ISS (International Space Station)! We'll start looking at the [ISS API documentation](https://wheretheiss.at/w/developer)

<h2 style="color: #008080;">Endpoints</h2>

#### Accessing an **endpoint**

APIs always need to provide documentation for their various services: **endpoints**.  Each endpoint is a different URL.

In [2]:
# We'll use the endpoint satellites, we read it gives us information about satellites
url = "https://api.wheretheiss.at/v1/satellites"

**Examples**
- Satellite details: `https://api.wheretheiss.at/v1/satellites`
- ISS position: `https://api.wheretheiss.at/v1/satellites/25544`
- Coordinates information: `https://api.wheretheiss.at/v1/coordinates/37.795517,-122.393693`

This API allows you to access various data related to the International Space Station (ISS), including its current, past, or future position, timezone information for specific coordinates, and more.

**Key Features**
- **Authentication**: No authentication is currently required, but future endpoints may include this.
- **Rate Limiting**: Limited to approximately 1 request per second.
- **Responses**: Default to JSON format, with optional parameters to modify response appearance.
- **Endpoints**: Several endpoints provide different types of information:
    - **satellites**: Information about satellites, including the ISS.

<h2 style="color: #008080;">GET</h2>

Making a `GET request` to the API is simply a call to a `URL` that returns information.

Here is an example on how to make a request with Python:

```python
url = "https://api.example.com/products"
response = requests.get(url)

if response.status_code == 200:
    products = response.json()
    # Now you can analyze and work with the products data in Python
```

In [4]:
response = requests.get(url)
data = response.json()

In [5]:
data

[{'name': 'iss', 'id': 25544}]

In [6]:
type(data)

list

Sometimes we can pass **parameters** to an API endpoint, similar to when we pass parameters to a Python function.

- API parameters are specific values that you include in a request to an API endpoint to filter, sort, or detail the data that you want to retrieve. They allow you to customize the request to get exactly the information you need.

- There are several types of parameters that can be used in API requests, such as Path Parameters, Query Parameters, Header Parameters and Request Body Parameters. Let's look at them with an example using another endpoint.

<h2 style="color: #008080;">Path Parameters</h2>

- **Endpoints**: Several endpoints provide different types of information:
    - **satellites**: Information about satellites, including the ISS.
    - **satellites/[id]**: Position, velocity, and related information for a satellite.

In [10]:
data

[{'name': 'iss', 'id': 25544}]

In [13]:
str(data[0]["id"])

'25544'

In [12]:
key = str(data[0]["id"])

In [14]:
iss = "https://api.wheretheiss.at/v1/satellites/"+key

In [16]:
iss

'https://api.wheretheiss.at/v1/satellites/25544'

In [19]:
response = requests.get(iss)
data = response.json()

In [20]:
data

{'name': 'iss',
 'id': 25544,
 'latitude': 35.253152973839,
 'longitude': 158.50868498532,
 'altitude': 419.89015711294,
 'velocity': 27589.874462065,
 'visibility': 'eclipsed',
 'footprint': 4506.9045870294,
 'timestamp': 1727516205,
 'daynum': 2460581.9005208,
 'solar_lat': -2.2874925321348,
 'solar_lon': 33.44129037719,
 'units': 'kilometers'}

##### **Path Parameters**

These are embedded in the URL path and are used to identify a specific resource. For example, in the URL above `https://api.wheretheiss.at/v1/satellites/25544`, the number `25544` is a path parameter that identifies a specific sattelite.

<h2 style="color: #008080;">Where is my Data?</h2>

In [21]:
import pandas as pd

In [25]:
df = pd.DataFrame([data])

In [23]:
df

,name,id,latitude,longitude,altitude,velocity,visibility,footprint,timestamp,daynum,solar_lat,solar_lon,units
0,iss,25544,35.253153,158.508685,419.890157,27589.874462,eclipsed,4506.904587,1727516205,2.460582e+06,-2.287493,33.44129,kilometers

<h2 style="color: #008080;">More Data = More Requests</h2>

In [ ]:
# pip install time

In [26]:
import time

In [42]:
positions = []

for i in range(15):
    response = requests.get(iss)
    data2 = response.json()
    positions.append(data2)
    time.sleep(0.5)

In [ ]:
type(positions)

In [44]:
df2 = pd.DataFrame(positions)

In [45]:
df2

,name,id,latitude,longitude,altitude,velocity,visibility,footprint,timestamp,daynum,solar_lat,solar_lon,units
0,iss,25544,14.750477,178.496743,419.715580,27577.909314,eclipsed,4506.016174,1727516643,2.460582e+06,-2.289464,31.615867,kilometers
1,iss,25544,14.700649,178.535365,419.718815,27577.876002,eclipsed,4506.032642,1727516644,2.460582e+06,-2.289468,31.611699,kilometers
2,iss,25544,14.650811,178.573968,419.722073,27577.842660,eclipsed,4506.049222,1727516645,2.460582e+06,-2.289473,31.607532,kilometers
3,iss,25544,14.600968,178.612551,419.725352,27577.809290,eclipsed,4506.065912,1727516646,2.460582e+06,-2.289477,31.603364,kilometers
4,iss,25544,14.551117,178.651114,419.728654,27577.775890,eclipsed,4506.082714,1727516647,2.460582e+06,-2.289482,31.599196,kilometers
5,iss,25544,14.451390,178.728183,419.735322,27577.709003,eclipsed,4506.116651,1727516649,2.460582e+06,-2.289491,31.590861,kilometers
6,iss,25544,14.401515,178.766689,419.738689,27577.675514,eclipsed,4506.133786,1727516650,2.460582e+06,-2.289495,31.586694,kilometers
7,iss,25544,14.351632,178.805176,419.742078,27577.641997,eclipsed,4506.151034,1727516651,2.460582e+06,-2.289500,31.582526,kilometers
8,iss,25544,14.301740,178.843646,419.745489,27577.608448,eclipsed,4506.168394,1727516652,2.460582e+06,-2.289504,31.578358,kilometers
9,iss,25544,14.251842,178.882095,419.748921,27577.574872,eclipsed,4506.185865,1727516653,2.460582e+06,-2.289509,31.574191,kilometers
10,iss,25544,14.201936,178.920525,419.752376,27577.541266,eclipsed,4506.203448,1727516654,2.460582e+06,-2.289513,31.570023,kilometers
11,iss,25544,14.152022,178.958936,419.755853,27577.507630,eclipsed,4506.221143,1727516655,2.460582e+06,-2.289518,31.565855,kilometers
12,iss,25544,14.102101,178.997329,419.759352,27577.473965,eclipsed,4506.238951,1727516656,2.460582e+06,-2.289522,31.561688,kilometers
13,iss,25544,14.002236,179.074060,419.766417,27577.406547,eclipsed,4506.274904,1727516658,2.460582e+06,-2.289531,31.553353,kilometers
14,iss,25544,13.952292,179.112397,419.769982,27577.372794,eclipsed,4506.293049,1727516659,2.460582e+06,-2.289536,31.549185,kilometers

In [47]:
df2.duplicated().sum()

0

In [48]:
df2 = df2.drop(columns=["id"])
df2 = df2.set_index("name")

In [49]:
df2

,latitude,longitude,altitude,velocity,visibility,footprint,timestamp,daynum,solar_lat,solar_lon,units
name,,,,,,,,,,,
iss,14.750477,178.496743,419.715580,27577.909314,eclipsed,4506.016174,1727516643,2.460582e+06,-2.289464,31.615867,kilometers
iss,14.700649,178.535365,419.718815,27577.876002,eclipsed,4506.032642,1727516644,2.460582e+06,-2.289468,31.611699,kilometers
iss,14.650811,178.573968,419.722073,27577.842660,eclipsed,4506.049222,1727516645,2.460582e+06,-2.289473,31.607532,kilometers
iss,14.600968,178.612551,419.725352,27577.809290,eclipsed,4506.065912,1727516646,2.460582e+06,-2.289477,31.603364,kilometers
iss,14.551117,178.651114,419.728654,27577.775890,eclipsed,4506.082714,1727516647,2.460582e+06,-2.289482,31.599196,kilometers
iss,14.451390,178.728183,419.735322,27577.709003,eclipsed,4506.116651,1727516649,2.460582e+06,-2.289491,31.590861,kilometers
iss,14.401515,178.766689,419.738689,27577.675514,eclipsed,4506.133786,1727516650,2.460582e+06,-2.289495,31.586694,kilometers
iss,14.351632,178.805176,419.742078,27577.641997,eclipsed,4506.151034,1727516651,2.460582e+06,-2.289500,31.582526,kilometers
iss,14.301740,178.843646,419.745489,27577.608448,eclipsed,4506.168394,1727516652,2.460582e+06,-2.289504,31.578358,kilometers
iss,14.251842,178.882095,419.748921,27577.574872,eclipsed,4506.185865,1727516653,2.460582e+06,-2.289509,31.574191,kilometers
iss,14.201936,178.920525,419.752376,27577.541266,eclipsed,4506.203448,1727516654,2.460582e+06,-2.289513,31.570023,kilometers
iss,14.152022,178.958936,419.755853,27577.507630,eclipsed,4506.221143,1727516655,2.460582e+06,-2.289518,31.565855,kilometers
iss,14.102101,178.997329,419.759352,27577.473965,eclipsed,4506.238951,1727516656,2.460582e+06,-2.289522,31.561688,kilometers
iss,14.002236,179.074060,419.766417,27577.406547,eclipsed,4506.274904,1727516658,2.460582e+06,-2.289531,31.553353,kilometers
iss,13.952292,179.112397,419.769982,27577.372794,eclipsed,4506.293049,1727516659,2.460582e+06,-2.289536,31.549185,kilometers